@echo off
echo 🌕 Initializing Lunar Hazard Detective...
echo 📂 Activating Virtual Environment...
call .venv\Scripts\activate
echo 🛠️ Verifying dependencies...
pip install -r requirements.txt
echo 🚀 Launching Mission Control Dashboard...
python -m streamlit run app.py
pause